/// Perf event configurations in this file are generated by "parse_perflist.py".
///
/// We can also make this list based on [1] and [2], but currently it's just
/// easier for me to parse the output of perf-list.
///
/// Note that some events are commented out because I don't have time to give
/// them abbreviations within 16 characters. (it's currently a hard limit for
/// showing event name, see also `main.zig::printMeasurement()`)
///
/// [1]: https://perfmon-events.intel.com/
/// [2]: https://github.com/torvalds/linux/blob/7ff71e6d/arch/x86/events/intel/core.c
const events = @import("../events.zig");

pub const avaliable_perf_measurements = [_]events.PerfMeasurement{
    // cpu
    .{
        .name = "branch_inst",
        .full_name = "branch-instructions",
        .config = .{ .raw = .{ .event = 0xc4, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "bus-cycles",
        .full_name = "bus-cycles",
        .config = .{ .raw = .{ .event = 0x3c, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "mem-loads",
        .full_name = "mem-loads",
        .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "mem-stores",
        .full_name = "mem-stores",
        .config = .{ .raw = .{ .event = 0xd0, .umask = 0x82, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "ref-cycles",
        .full_name = "ref-cycles",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x03, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "slots",
        .full_name = "slots",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "topdown-bad-spec",
        .full_name = "topdown-bad-spec",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x81, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "topdown-be-bound",
        .full_name = "topdown-be-bound",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x83, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "topdown-fe-bound",
        .full_name = "topdown-fe-bound",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x82, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "topdown-retiring",
        .full_name = "topdown-retiring",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_core/c6-residency/",
    //     .config = .{ .raw = .{ .event = 0x02, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_core/c7-residency/",
    //     .config = .{ .raw = .{ .event = 0x03, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c10-residency/",
    //     .config = .{ .raw = .{ .event = 0x06, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c2-residency/",
    //     .config = .{ .raw = .{ .event = 0x00, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c3-residency/",
    //     .config = .{ .raw = .{ .event = 0x01, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c6-residency/",
    //     .config = .{ .raw = .{ .event = 0x02, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c7-residency/",
    //     .config = .{ .raw = .{ .event = 0x03, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c8-residency/",
    //     .config = .{ .raw = .{ .event = 0x04, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cstate_pkg/c9-residency/",
    //     .config = .{ .raw = .{ .event = 0x05, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "msr/aperf/",
        .full_name = "msr/aperf/",
        .config = .{ .raw = .{ .event = 0x01, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "msr/cpu_thermal_margin/",
    //     .config = .{ .raw = .{ .event = 0x07, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "msr/mperf/",
        .full_name = "msr/mperf/",
        .config = .{ .raw = .{ .event = 0x02, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "msr/pperf/",
        .full_name = "msr/pperf/",
        .config = .{ .raw = .{ .event = 0x03, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "msr/smi/",
        .full_name = "msr/smi/",
        .config = .{ .raw = .{ .event = 0x04, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "msr/tsc/",
        .full_name = "msr/tsc/",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "power/energy-cores/",
    //     .config = .{ .raw = .{ .event = 0x01, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "power/energy-gpu/",
    //     .config = .{ .raw = .{ .event = 0x04, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "power/energy-pkg/",
    //     .config = .{ .raw = .{ .event = 0x02, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uncore_clock/clockticks/",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uncore_imc_free_running/data_read/",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uncore_imc_free_running/data_total/",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uncore_imc_free_running/data_write/",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x30, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // cache
    .{
        .name = "l1d.replacement",
        .full_name = "l1d.replacement",
        .config = .{ .raw = .{ .event = 0x51, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l1d_pend_miss.fb_full",
    //     .config = .{ .raw = .{ .event = 0x48, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l1d_pend_miss.fb_full_periods",
    //     .config = .{ .raw = .{ .event = 0x48, .umask = 0x02, .edge = 0x01, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l1d_pend_miss.l2_stall",
    //     .config = .{ .raw = .{ .event = 0x48, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l1d_pend_miss.pending",
    //     .config = .{ .raw = .{ .event = 0x48, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l1d_pend_miss.pending_cycles",
    //     .config = .{ .raw = .{ .event = 0x48, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    .{
        .name = "l2_lines_in.all",
        .full_name = "l2_lines_in.all",
        .config = .{ .raw = .{ .event = 0xf1, .umask = 0x1f, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_lines_out.non_silent",
    //     .config = .{ .raw = .{ .event = 0xf2, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_lines_out.silent",
    //     .config = .{ .raw = .{ .event = 0xf2, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.all_code_rd",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0xe4, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.all_demand_data_rd",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0xe1, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "l2_rqsts.all_rfo",
        .full_name = "l2_rqsts.all_rfo",
        .config = .{ .raw = .{ .event = 0x24, .umask = 0xe2, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.code_rd_hit",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0xc4, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.code_rd_miss",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0x24, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.demand_data_rd_hit",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0xc1, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.demand_data_rd_miss",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0x21, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "l2_rqsts.miss",
        .full_name = "l2_rqsts.miss",
        .config = .{ .raw = .{ .event = 0x24, .umask = 0x3f, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.references",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0xff, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "l2_rqsts.rfo_hit",
        .full_name = "l2_rqsts.rfo_hit",
        .config = .{ .raw = .{ .event = 0x24, .umask = 0xc2, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.rfo_miss",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0x22, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.swpf_hit",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0xc8, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "l2_rqsts.swpf_miss",
    //     .config = .{ .raw = .{ .event = 0x24, .umask = 0x28, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "l2_trans.l2_wb",
        .full_name = "l2_trans.l2_wb",
        .config = .{ .raw = .{ .event = 0xf0, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "lock_cycles.cache_lock_duration",
    //     .config = .{ .raw = .{ .event = 0x63, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "longest_lat_cache.miss",
    //     .config = .{ .raw = .{ .event = 0x2e, .umask = 0x41, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.all_loads",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x81, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.all_stores",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x82, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.any",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x83, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.lock_loads",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x21, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.split_loads",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x41, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.split_stores",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x42, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.stlb_miss_loads",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x11, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_inst_retired.stlb_miss_stores",
    //     .config = .{ .raw = .{ .event = 0xd0, .umask = 0x12, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_l3_hit_retired.xsnp_fwd",
    //     .config = .{ .raw = .{ .event = 0xd2, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_l3_hit_retired.xsnp_miss",
    //     .config = .{ .raw = .{ .event = 0xd2, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_l3_hit_retired.xsnp_no_fwd",
    //     .config = .{ .raw = .{ .event = 0xd2, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_l3_hit_retired.xsnp_none",
    //     .config = .{ .raw = .{ .event = 0xd2, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_misc_retired.uc",
    //     .config = .{ .raw = .{ .event = 0xd4, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.fb_hit",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.l1_hit",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.l1_miss",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.l2_hit",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.l2_miss",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.l3_hit",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_load_retired.l3_miss",
    //     .config = .{ .raw = .{ .event = 0xd1, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "ocr.demand_data_rd.l3_hit.snoop_hit_with_fwd",
    //     .config = .{ .raw = .{ .event = 0xb7, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "ocr.demand_data_rd.l3_hit.snoop_hitm",
    //     .config = .{ .raw = .{ .event = 0xb7, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "ocr.demand_rfo.l3_hit.snoop_hitm",
    //     .config = .{ .raw = .{ .event = 0xb7, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests.all_data_rd",
    //     .config = .{ .raw = .{ .event = 0xb0, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests.all_requests",
    //     .config = .{ .raw = .{ .event = 0xb0, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests.demand_data_rd",
    //     .config = .{ .raw = .{ .event = 0xb0, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests.demand_rfo",
    //     .config = .{ .raw = .{ .event = 0xb0, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.all_data_rd",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.cycles_with_data_rd",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.cycles_with_demand_data_rd",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.cycles_with_demand_rfo",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.demand_data_rd",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.demand_data_rd_ge_6",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x06 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests_outstanding.demand_rfo",
    //     .config = .{ .raw = .{ .event = 0x60, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "sq_misc.bus_lock",
        .full_name = "sq_misc.bus_lock",
        .config = .{ .raw = .{ .event = 0xf4, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "sq_misc.sq_full",
        .full_name = "sq_misc.sq_full",
        .config = .{ .raw = .{ .event = 0xf4, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "sw_prefetch_access.nta",
    //     .config = .{ .raw = .{ .event = 0x32, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "sw_prefetch_access.prefetchw",
    //     .config = .{ .raw = .{ .event = 0x32, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "sw_prefetch_access.t0",
    //     .config = .{ .raw = .{ .event = 0x32, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "sw_prefetch_access.t1_t2",
    //     .config = .{ .raw = .{ .event = 0x32, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // floating point
    .{
        .name = "assists.fp",
        .full_name = "assists.fp",
        .config = .{ .raw = .{ .event = 0xc1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.128b_packed_double",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.128b_packed_single",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.256b_packed_double",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.256b_packed_single",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.4_flops",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x18, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.512b_packed_double",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.512b_packed_single",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.8_flops",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x60, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.scalar",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x03, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.scalar_double",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.scalar_single",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "fp_arith_inst_retired.vector",
    //     .config = .{ .raw = .{ .event = 0xc7, .umask = 0xfc, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // frontend
    .{
        .name = "baclears.any",
        .full_name = "baclears.any",
        .config = .{ .raw = .{ .event = 0xe6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "decode.lcp",
        .full_name = "decode.lcp",
        .config = .{ .raw = .{ .event = 0x87, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dsb2mite_switches.count",
    //     .config = .{ .raw = .{ .event = 0xab, .umask = 0x02, .edge = 0x01, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dsb2mite_switches.penalty_cycles",
    //     .config = .{ .raw = .{ .event = 0xab, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.any_dsb_miss",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.dsb_miss",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.itlb_miss",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.l1i_miss",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.l2_miss",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_1",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_128",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_16",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_2",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_256",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_2_bubbles_ge_1",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_32",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_4",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_512",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_64",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.latency_ge_8",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "frontend_retired.stlb_miss",
    //     .config = .{ .raw = .{ .event = 0xc6, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "icache_16b.ifdata_stall",
    //     .config = .{ .raw = .{ .event = 0x80, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "icache_64b.iftag_hit",
    //     .config = .{ .raw = .{ .event = 0x83, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "icache_64b.iftag_miss",
    //     .config = .{ .raw = .{ .event = 0x83, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "icache_64b.iftag_stall",
    //     .config = .{ .raw = .{ .event = 0x83, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "icache_data.stalls",
    //     .config = .{ .raw = .{ .event = 0x80, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "icache_tag.stalls",
    //     .config = .{ .raw = .{ .event = 0x83, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "idq.dsb_cycles_any",
    //     .config = .{ .raw = .{ .event = 0x79, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "idq.dsb_cycles_ok",
    //     .config = .{ .raw = .{ .event = 0x79, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x05 } },
    // },
    .{
        .name = "idq.dsb_uops",
        .full_name = "idq.dsb_uops",
        .config = .{ .raw = .{ .event = 0x79, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "idq.mite_cycles_any",
    //     .config = .{ .raw = .{ .event = 0x79, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "idq.mite_cycles_ok",
    //     .config = .{ .raw = .{ .event = 0x79, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x05 } },
    // },
    .{
        .name = "idq.mite_uops",
        .full_name = "idq.mite_uops",
        .config = .{ .raw = .{ .event = 0x79, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "idq.ms_cycles_any",
    //     .config = .{ .raw = .{ .event = 0x79, .umask = 0x30, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    .{
        .name = "idq.ms_switches",
        .full_name = "idq.ms_switches",
        .config = .{ .raw = .{ .event = 0x79, .umask = 0x30, .edge = 0x01, .inv = 0x00, .cmask = 0x01 } },
    },
    .{
        .name = "idq.ms_uops",
        .full_name = "idq.ms_uops",
        .config = .{ .raw = .{ .event = 0x79, .umask = 0x30, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "idq_uops_nd_core",
        .full_name = "idq_uops_not_delivered.core",
        .config = .{ .raw = .{ .event = 0x9c, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "idq_uops_nd_c0",
        .full_name = "idq_uops_not_delivered.cycles_0_uops_deliv.core",
        .config = .{ .raw = .{ .event = 0x9c, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x05 } },
    },
    .{
        .name = "idq_uops_nd_cfe",
        .full_name = "idq_uops_not_delivered.cycles_fe_was_ok",
        .config = .{ .raw = .{ .event = 0x9c, .umask = 0x01, .edge = 0x00, .inv = 0x01, .cmask = 0x01 } },
    },
    // // memory
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.stalls_l3_miss",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x06, .edge = 0x00, .inv = 0x00, .cmask = 0x06 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "machine_clears.memory_ordering",
    //     .config = .{ .raw = .{ .event = 0xc3, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_128",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_16",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_256",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_32",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_4",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_512",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_64",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "mem_trans_retired.load_latency_gt_8",
    //     .config = .{ .raw = .{ .event = 0xcd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "offcore_requests.l3_miss_demand_data_rd",
    //     .config = .{ .raw = .{ .event = 0xb0, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.aborted",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.aborted_events",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.aborted_mem",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.aborted_memtype",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.aborted_unfriendly",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.commit",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rtm_retired.start",
    //     .config = .{ .raw = .{ .event = 0xc9, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "tx_exec.misc2",
        .full_name = "tx_exec.misc2",
        .config = .{ .raw = .{ .event = 0x5d, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "tx_exec.misc3",
        .full_name = "tx_exec.misc3",
        .config = .{ .raw = .{ .event = 0x5d, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "tx_mem.abort_capacity_read",
    //     .config = .{ .raw = .{ .event = 0x54, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "tx_mem.abort_capacity_write",
    //     .config = .{ .raw = .{ .event = 0x54, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "tx_mem.abort_conflict",
    //     .config = .{ .raw = .{ .event = 0x54, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // // other
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "core_power.lvl0_turbo_license",
    //     .config = .{ .raw = .{ .event = 0x28, .umask = 0x07, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "core_power.lvl1_turbo_license",
    //     .config = .{ .raw = .{ .event = 0x28, .umask = 0x18, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "core_power.lvl2_turbo_license",
    //     .config = .{ .raw = .{ .event = 0x28, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "ocr.streaming_wr.any_response",
    //     .config = .{ .raw = .{ .event = 0xb7, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // // pipeline
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "arith.divider_active",
    //     .config = .{ .raw = .{ .event = 0x14, .umask = 0x09, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    .{
        .name = "assists.any",
        .full_name = "assists.any",
        .config = .{ .raw = .{ .event = 0xc1, .umask = 0x07, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.all_branches",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.cond",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x11, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.cond_ntaken",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.cond_taken",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.far_branch",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.indirect",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.near_call",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.near_return",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_inst_retired.near_taken",
    //     .config = .{ .raw = .{ .event = 0xc4, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.all_branches",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.cond",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x11, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.cond_ntaken",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.cond_taken",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.indirect",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.indirect_call",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.near_taken",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "br_misp_retired.ret",
    //     .config = .{ .raw = .{ .event = 0xc5, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.distributed",
    //     .config = .{ .raw = .{ .event = 0xec, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.one_thread_active",
    //     .config = .{ .raw = .{ .event = 0x3c, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.ref_distributed",
    //     .config = .{ .raw = .{ .event = 0x3c, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.ref_tsc",
    //     .config = .{ .raw = .{ .event = 0x00, .umask = 0x03, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.ref_xclk",
    //     .config = .{ .raw = .{ .event = 0x3c, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.thread",
    //     .config = .{ .raw = .{ .event = 0x3c, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cpu_clk_unhalted.thread_p",
    //     .config = .{ .raw = .{ .event = 0x3c, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.cycles_l1d_miss",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x08 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.cycles_l2_miss",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.cycles_mem_any",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x10 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.stalls_l1d_miss",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x0c, .edge = 0x00, .inv = 0x00, .cmask = 0x0c } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.stalls_l2_miss",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x05, .edge = 0x00, .inv = 0x00, .cmask = 0x05 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.stalls_mem_any",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x14, .edge = 0x00, .inv = 0x00, .cmask = 0x14 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "cycle_activity.stalls_total",
    //     .config = .{ .raw = .{ .event = 0xa3, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x04 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.1_ports_util",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.2_ports_util",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.3_ports_util",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.4_ports_util",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.bound_on_loads",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x21, .edge = 0x00, .inv = 0x00, .cmask = 0x05 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.bound_on_stores",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x02 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "exe_activity.exe_bound_0_ports",
    //     .config = .{ .raw = .{ .event = 0xa6, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "ild_stall.lcp",
        .full_name = "ild_stall.lcp",
        .config = .{ .raw = .{ .event = 0x87, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "inst_decoded.decoders",
    //     .config = .{ .raw = .{ .event = 0x55, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "inst_retired.any",
        .full_name = "inst_retired.any",
        .config = .{ .raw = .{ .event = 0xc0, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "inst_retired.any_p",
    //     .config = .{ .raw = .{ .event = 0xc0, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "inst_retired.nop",
        .full_name = "inst_retired.nop",
        .config = .{ .raw = .{ .event = 0xc0, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "inst_retired.prec_dist",
    //     .config = .{ .raw = .{ .event = 0x00, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "int_misc.all_recovery_cycles",
    //     .config = .{ .raw = .{ .event = 0x0d, .umask = 0x03, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "int_misc.clear_resteer_cycles",
    //     .config = .{ .raw = .{ .event = 0x0d, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "int_misc.clears_count",
    //     .config = .{ .raw = .{ .event = 0x0d, .umask = 0x01, .edge = 0x01, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "int_misc.recovery_cycles",
    //     .config = .{ .raw = .{ .event = 0x0d, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "int_misc.uop_dropping",
    //     .config = .{ .raw = .{ .event = 0x0d, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "ld_blocks.no_sr",
        .full_name = "ld_blocks.no_sr",
        .config = .{ .raw = .{ .event = 0x03, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "ld_blks_store_fw",
        .full_name = "ld_blocks.store_forward",
        .config = .{ .raw = .{ .event = 0x03, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "ld_blocks_partial.address_alias",
    //     .config = .{ .raw = .{ .event = 0x07, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "load_hit_prefetch.swpf",
    //     .config = .{ .raw = .{ .event = 0x4c, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "lsd.cycles_active",
    //     .config = .{ .raw = .{ .event = 0xa8, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    .{
        .name = "lsd.cycles_ok",
        .full_name = "lsd.cycles_ok",
        .config = .{ .raw = .{ .event = 0xa8, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x05 } },
    },
    .{
        .name = "lsd.uops",
        .full_name = "lsd.uops",
        .config = .{ .raw = .{ .event = 0xa8, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "machine_clears.count",
    //     .config = .{ .raw = .{ .event = 0xc3, .umask = 0x01, .edge = 0x01, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "machine_clears.smc",
    //     .config = .{ .raw = .{ .event = 0xc3, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "misc_retired.lbr_inserts",
    //     .config = .{ .raw = .{ .event = 0xcc, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "misc_retired.pause_inst",
    //     .config = .{ .raw = .{ .event = 0xcc, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "res_stalls_sb",
        .full_name = "resource_stalls.sb",
        .config = .{ .raw = .{ .event = 0xa2, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "res_stalls_score",
        .full_name = "resource_stalls.scoreboard",
        .config = .{ .raw = .{ .event = 0xa2, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rs_events.empty_cycles",
    //     .config = .{ .raw = .{ .event = 0x5e, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "rs_events.empty_end",
    //     .config = .{ .raw = .{ .event = 0x5e, .umask = 0x01, .edge = 0x01, .inv = 0x01, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "topdown.backend_bound_slots",
    //     .config = .{ .raw = .{ .event = 0xa4, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "topdown.br_mispredict_slots",
    //     .config = .{ .raw = .{ .event = 0xa4, .umask = 0x08, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "topdown.slots",
        .full_name = "topdown.slots",
        .config = .{ .raw = .{ .event = 0x00, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "topdown.slots_p",
        .full_name = "topdown.slots_p",
        .config = .{ .raw = .{ .event = 0xa4, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_decoded.dec0",
    //     .config = .{ .raw = .{ .event = 0x56, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_0",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_1",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_2_3",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_4_9",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_5",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_6",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x40, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_dispatched.port_7_8",
    //     .config = .{ .raw = .{ .event = 0xa1, .umask = 0x80, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.core",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.core_cycles_ge_1",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.core_cycles_ge_2",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x02 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.core_cycles_ge_3",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x03 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.core_cycles_ge_4",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x04 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.cycles_ge_1",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.cycles_ge_2",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x02 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.cycles_ge_3",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x03 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.cycles_ge_4",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x04 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.stall_cycles",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x01, .edge = 0x00, .inv = 0x01, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.thread",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "uops_executed.x87",
    //     .config = .{ .raw = .{ .event = 0xb1, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    .{
        .name = "uops_issued_any",
        .full_name = "uops_issued.any",
        .config = .{ .raw = .{ .event = 0x0e, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "uops_issued_sta",
        .full_name = "uops_issued.stall_cycles",
        .config = .{ .raw = .{ .event = 0x0e, .umask = 0x01, .edge = 0x00, .inv = 0x01, .cmask = 0x01 } },
    },
    .{
        .name = "uops_issued_vwm",
        .full_name = "uops_issued.vector_width_mismatch",
        .config = .{ .raw = .{ .event = 0x0e, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "uops_retired_sl",
        .full_name = "uops_retired.slots",
        .config = .{ .raw = .{ .event = 0xc2, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    .{
        .name = "uops_retired_sta",
        .full_name = "uops_retired.stall_cycles",
        .config = .{ .raw = .{ .event = 0xc2, .umask = 0x02, .edge = 0x00, .inv = 0x01, .cmask = 0x01 } },
    },
    .{
        .name = "uops_retired_tt",
        .full_name = "uops_retired.total_cycles",
        .config = .{ .raw = .{ .event = 0xc2, .umask = 0x02, .edge = 0x00, .inv = 0x01, .cmask = 0x0a } },
    },
    // // uncore interconnect
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_coh_trk_requests.all",
    //     .config = .{ .raw = .{ .event = 0x84, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_dat_occupancy.all",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_dat_occupancy.rd",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_dat_requests.rd",
    //     .config = .{ .raw = .{ .event = 0x81, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_ifa_occupancy.all",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_req_trk_occupancy.drd",
    //     .config = .{ .raw = .{ .event = 0x80, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_req_trk_request.drd",
    //     .config = .{ .raw = .{ .event = 0x81, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_trk_occupancy.all",
    //     .config = .{ .raw = .{ .event = 0x80, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_trk_occupancy.rd",
    //     .config = .{ .raw = .{ .event = 0x80, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_trk_requests.all",
    //     .config = .{ .raw = .{ .event = 0x81, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_arb_trk_requests.rd",
    //     .config = .{ .raw = .{ .event = 0x81, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // // uncore memory
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_mc0_rdcas_count_freerun",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_mc0_total_reqcount_freerun",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "unc_mc0_wrcas_count_freerun",
    //     .config = .{ .raw = .{ .event = 0xff, .umask = 0x30, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // uncore other
    .{
        .name = "unc_clock.socket",
        .full_name = "unc_clock.socket",
        .config = .{ .raw = .{ .event = 0xff, .umask = 0x00, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    },
    // // virtual memory
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_load_misses.stlb_hit",
    //     .config = .{ .raw = .{ .event = 0x08, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_load_misses.walk_active",
    //     .config = .{ .raw = .{ .event = 0x08, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_load_misses.walk_completed",
    //     .config = .{ .raw = .{ .event = 0x08, .umask = 0x0e, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_load_misses.walk_completed_2m_4m",
    //     .config = .{ .raw = .{ .event = 0x08, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_load_misses.walk_completed_4k",
    //     .config = .{ .raw = .{ .event = 0x08, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_load_misses.walk_pending",
    //     .config = .{ .raw = .{ .event = 0x08, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_store_misses.stlb_hit",
    //     .config = .{ .raw = .{ .event = 0x49, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_store_misses.walk_active",
    //     .config = .{ .raw = .{ .event = 0x49, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_store_misses.walk_completed",
    //     .config = .{ .raw = .{ .event = 0x49, .umask = 0x0e, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_store_misses.walk_completed_2m_4m",
    //     .config = .{ .raw = .{ .event = 0x49, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_store_misses.walk_completed_4k",
    //     .config = .{ .raw = .{ .event = 0x49, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "dtlb_store_misses.walk_pending",
    //     .config = .{ .raw = .{ .event = 0x49, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "itlb_misses.stlb_hit",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "itlb_misses.walk_active",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x01 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "itlb_misses.walk_completed",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x0e, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "itlb_misses.walk_completed_2m_4m",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x04, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "itlb_misses.walk_completed_4k",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x02, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "itlb_misses.walk_pending",
    //     .config = .{ .raw = .{ .event = 0x85, .umask = 0x10, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "tlb_flush.dtlb_thread",
    //     .config = .{ .raw = .{ .event = 0xbd, .umask = 0x01, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
    // .{
    //     .name = "PLEASE_RENAME_THIS_WITHIN_16_CHARS",
    //     .full_name = "tlb_flush.stlb_any",
    //     .config = .{ .raw = .{ .event = 0xbd, .umask = 0x20, .edge = 0x00, .inv = 0x00, .cmask = 0x00 } },
    // },
};
